# Generated by Django 5.1.7 on 2025-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='h1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='seo',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
