# Generated by Django 5.1.7 on 2025-03-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seo_h1_seo_image_seo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='h1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='page',
            field=models.CharField(max_length=100, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка'),
        ),
    ]
