# Generated by Django 5.1.7 on 2025-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_seo_description_alter_seo_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='../static/images/', verbose_name='Изображение'),
        ),
    ]
