# Generated by Django 5.1.7 on 2025-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_seo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
