# Generated by Django 5.1.7 on 2025-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_seo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контакт')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='h1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
