# Generated by Django 5.1.7 on 2025-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_applications_alter_seo_description_alter_seo_h1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('label_image', models.FileField(blank=True, null=True, upload_to='images/scenaries/', verbose_name='Лэйбл')),
            ],
            options={
                'verbose_name': 'Сценарии',
                'verbose_name_plural': 'Сценарии',
            },
        ),
    ]
