# Generated by Django 5.1.7 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_scenaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание страницы'),
        ),
    ]
